# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy NodeJS and Wordpress Site
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            rm -rf deployment
            mkdir deployment
            cd deployment
            git clone --depth 1 https://github.com/K-JAX/jThompsonSite.git
            cd jThompsonSite/frontend && npm i && npm run build && cd ../..
            rm -rf /var/www/html/jthompsonarch/frontend
            cp -R jThompsonSite/frontend /var/www/html/jthompsonarch/
            rm -rf /var/www/wordpress/wp-content/themes
            cp -R jThompsonSite/wordpress/wp-content/themes /var/www/wordpress/wp-content/themes
